CREATE TABLE addresses
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country          VARCHAR(255),
    county           VARCHAR(255),
    city             VARCHAR(255),
    street           VARCHAR(255),
    street_number    VARCHAR(255),
    block            VARCHAR(255),
    staircase        VARCHAR(255),
    floor            VARCHAR(255),
    apartment_number VARCHAR(255),
    CONSTRAINT pk_addresses PRIMARY KEY (id)
);

CREATE TABLE legal_entities
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tax_identification_number VARCHAR(255)                            NOT NULL,
    trade_registry_number     VARCHAR(255)                            NOT NULL,
    name                      VARCHAR(255)                            NOT NULL,
    email                     VARCHAR(255),
    phone_number              VARCHAR(255),
    establishment_date        date,
    address_id                BIGINT,
    is_active                 BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_legal_entities PRIMARY KEY (id)
);

CREATE TABLE user_legal_entities
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT,
    legal_entity_id BIGINT,
    business_role   VARCHAR(255),
    CONSTRAINT pk_user_legal_entities PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    system_role VARCHAR(255),
    email       VARCHAR(255),
    password    VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE user_legal_entities
    ADD CONSTRAINT uc_1d1b36314d053fa650a31f394 UNIQUE (user_id, legal_entity_id);

ALTER TABLE legal_entities
    ADD CONSTRAINT uc_legal_entities_taxidentificationnumber UNIQUE (tax_identification_number);

ALTER TABLE legal_entities
    ADD CONSTRAINT FK_LEGAL_ENTITIES_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES addresses (id);

ALTER TABLE user_legal_entities
    ADD CONSTRAINT FK_USER_LEGAL_ENTITIES_ON_LEGAL_ENTITY FOREIGN KEY (legal_entity_id) REFERENCES legal_entities (id);

ALTER TABLE user_legal_entities
    ADD CONSTRAINT FK_USER_LEGAL_ENTITIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);