spring.application.name=backend

# datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/franchise-manager
spring.datasource.username=postgres
spring.datasource.password=admin

# hibernate configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

# redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

server.servlet.context-path=/franchise-manager

jwt.secret=${JWT_SECRET_KEY}

# Debug JWT auth
logging.level.github.patrik1339.backend.security=DEBUG
logging.level.github.patrik1339.backend.controller=ERROR